name: sys-benches

services:
  ops-bench:
    image: ops-bench:${USER:-brett}
    container_name: ops-bench
    command: sleep infinity
    working_dir: /workspace
    privileged: true
    environment:
      - HISTFILE=/home/${USER:-brett}/.workbenches-history/.zsh_history
      - DOCKER_HOST=unix:///var/run/docker.sock
